import fs from 'node:fs';
import path from 'node:path';
import { config } from './config.js';
import { generateVideo } from './grokVideo.js';
import { writeVideoConceptWithAI } from './omniroute.js';
import { uploadFile } from './drive.js';

const STATE_PATH = path.join(process.cwd(), 'autogen-state.json');

// Used only if OmniRoute isn't reachable when it's time to generate.
const FALLBACK_CONCEPTS = [
  'A Somali elder telling a folktale by firelight, warm golden light, cinematic close-up on expressive hands.',
  'A camel caravan crossing golden desert dunes at sunset, wide cinematic shot, dust catching the light.',
  'Hands weaving a traditional Somali basket, macro shot, warm natural light, slow and meditative.',
  'A busy Somali market at dawn, vibrant fabric colors, steam rising from tea stalls, handheld documentary feel.',
  'Waves crashing on the Somali coastline at golden hour, a lone fishing boat silhouette, cinematic drone shot.',
];

function todayKey() {
  return new Date().toISOString().slice(0, 10);
}

function loadState() {
  try {
    return JSON.parse(fs.readFileSync(STATE_PATH, 'utf8'));
  } catch {
    return { date: todayKey(), count: 0, lastGeneratedAt: null };
  }
}

function saveState(state) {
  fs.writeFileSync(STATE_PATH, JSON.stringify(state, null, 2));
}

async function pickConcept() {
  try {
    return await writeVideoConceptWithAI();
  } catch (err) {
    console.log(`Could not get an AI video concept (${err.message}), using a fallback idea instead.`);
    return FALLBACK_CONCEPTS[Math.floor(Math.random() * FALLBACK_CONCEPTS.length)];
  }
}

// Generates at most one video per call, respecting AUTO_GENERATE_DAILY_LIMIT
// and spacing generations evenly across the day so they don't all fire the
// moment the limit resets. Safe to call on every check cycle -- it's a no-op
// most of the time.
export async function maybeAutoGenerateVideo(auth) {
  if (!config.autoGenerateVideos) return;

  let state = loadState();
  if (state.date !== todayKey()) {
    state = { date: todayKey(), count: 0, lastGeneratedAt: null };
  }

  if (state.count >= config.autoGenerateDailyLimit) return;

  const spacingMs = (24 * 60 * 60 * 1000) / config.autoGenerateDailyLimit;
  if (state.lastGeneratedAt && Date.now() - state.lastGeneratedAt < spacingMs) return;

  const concept = await pickConcept();
  console.log(`Auto-generating a video with Grok Imagine: "${concept}"`);

  const localPath = await generateVideo(concept);
  const fileName = `grok-auto-${Date.now()}.mp4`;
  await uploadFile(auth, localPath, fileName);
  fs.unlink(localPath, () => {});

  state.count += 1;
  state.lastGeneratedAt = Date.now();
  saveState(state);

  console.log(`Auto-generated video uploaded to GK_JING as "${fileName}" (${state.count}/${config.autoGenerateDailyLimit} today).`);
}
