import fs from 'node:fs';
import path from 'node:path';
import { config } from './config.js';
import { generateVideo } from './grokVideo.js';
import { writeVideoConceptWithAI } from './omniroute.js';
import { uploadFile } from './drive.js';

const STATE_PATH = path.join(process.cwd(), 'autogen-state.json');

// Used only if OmniRoute isn't reachable when it's time to generate. Mixes
// broad, no-cultural-framing-needed viral bait with GK Legend Studio's
// Somali heritage lane -- both written with a first-second hook and real
// described sound, since Grok Imagine generates synced audio from the prompt.
const FALLBACK_CONCEPTS = [
  'A cat leaps and snatches a falling leaf out of mid-air in slow motion, the crunch of paws landing on a pile of autumn leaves, warm low afternoon light.',
  "A hand slices open a ripe mango in one clean cut revealing golden flesh, juice dripping immediately, the sharp thwack of the knife on the board, a busy Somali market's ambient chatter and tea-stall steam in the background.",
  'Rain suddenly hits a hot pan and steam bursts upward with a loud hiss, close-up macro shot, dramatic side lighting.',
  "A Somali drummer's hands slam down on a taal drum in perfect rhythm from the very first frame, sweat catching the light, the deep thud of each beat filling the scene.",
  'A perfectly stacked row of dominoes collapses in a chain reaction starting instantly, each click echoing sharply, camera tracking alongside at eye level.',
  'Golden tea pours in a high dramatic arc between two cups, the splash and clink of glass, steam rising against a sunset-lit Somali market stall, hum of nearby voices.',
];

function todayKey() {
  return new Date().toISOString().slice(0, 10);
}

function todaysTargetHours() {
  return config.autoGenerateHours.slice(0, config.autoGenerateDailyLimit);
}

function loadState() {
  try {
    const state = JSON.parse(fs.readFileSync(STATE_PATH, 'utf8'));
    if (!state.generatedHours) state.generatedHours = [];
    return state;
  } catch {
    return { date: todayKey(), generatedHours: [] };
  }
}

function saveState(state) {
  fs.writeFileSync(STATE_PATH, JSON.stringify(state, null, 2));
}

async function pickConcept() {
  try {
    return await writeVideoConceptWithAI();
  } catch (err) {
    console.log(`Could not get an AI video concept (${err.message}), using a fallback idea instead.`);
    return FALLBACK_CONCEPTS[Math.floor(Math.random() * FALLBACK_CONCEPTS.length)];
  }
}

// Generates at most one video per call, aiming for the configured hours in
// config.autoGenerateHours rather than just even spacing. Safe to call on
// every check cycle -- it's a no-op most of the time.
export async function maybeAutoGenerateVideo(auth) {
  if (!config.autoGenerateVideos) return;

  let state = loadState();
  if (state.date !== todayKey()) {
    state = { date: todayKey(), generatedHours: [] };
  }

  const targets = todaysTargetHours();
  if (state.generatedHours.length >= targets.length) return;

  const currentHour = new Date().getHours();
  const dueHour = targets.find((h) => currentHour >= h && !state.generatedHours.includes(h));
  if (dueHour === undefined) return;

  const concept = await pickConcept();
  console.log(`Auto-generating a video with Grok Imagine (${dueHour}:00 slot): "${concept}"`);

  const localPath = await generateVideo(concept);
  const fileName = `grok-auto-${Date.now()}.mp4`;
  await uploadFile(auth, localPath, fileName);
  fs.unlink(localPath, () => {});

  state.generatedHours.push(dueHour);
  saveState(state);

  console.log(`Auto-generated video uploaded as "${fileName}" (${state.generatedHours.length}/${targets.length} today).`);
}
