import 'dotenv/config';

function required(name) {
  const value = process.env[name];
  if (!value) {
    console.error(`Missing required setting: ${name}. Check your .env file (copy .env.example to .env and fill it in).`);
    process.exit(1);
  }
  return value;
}

export const config = {
  googleClientId: required('GOOGLE_CLIENT_ID'),
  googleClientSecret: required('GOOGLE_CLIENT_SECRET'),
  driveFolderId: required('DRIVE_FOLDER_ID'),
  doneFolderId: process.env.DONE_FOLDER_ID || '',
  mirrorFolderId: process.env.MIRROR_FOLDER_ID || '',
  // GK_JING's folder ID -- set this (independent of MIRROR_FOLDER_ID/mirroring)
  // so the script writes missing caption rows for GK_JING videos too, not
  // just its own GK_TERMINAL ones. Leave blank to skip this and only
  // caption GK_TERMINAL videos as before.
  gkJingFolderId: process.env.GK_JING_FOLDER_ID || '',
  canvaClientId: process.env.CANVA_CLIENT_ID || '',
  canvaClientSecret: process.env.CANVA_CLIENT_SECRET || '',
  canvaBrandTemplateId: process.env.CANVA_BRAND_TEMPLATE_ID || '',
  canvaTitleField: process.env.CANVA_TITLE_FIELD || 'title',
  pinterestCoversFolderId: process.env.PINTEREST_COVERS_FOLDER_ID || '',
  // Manual cover-image pool (see src/coverPool.js) -- Joe drops finished
  // cover images into this folder himself (any tool, exported by hand, no
  // Canva API/OAuth needed), and the script assigns the oldest untouched one
  // to each video that needs a cover, moving it into the "Used" subfolder
  // afterward. Defaults to the folder pair created 15 Sep 2026 so this works
  // with zero setup; override here only if Joe wants to point it elsewhere.
  coverPoolFolderId: process.env.COVER_POOL_FOLDER_ID || '1_2dyzrmG9wr_F67mKUHLIPOMczP2XgRl',
  coverPoolUsedFolderId: process.env.COVER_POOL_USED_FOLDER_ID || '12zc1JcJkeYfoG6oc_9CCwkrqHnvjUfSe',
  // The Make.com side's own done folder (GK_JING_DONE) -- mirroring needs to
  // know about it too, otherwise a video that's already finished on one side
  // and moved to its done folder looks "missing" to the still-pending other
  // side and gets copied right back, causing a duplicate post loop.
  mirrorDoneFolderId: process.env.MIRROR_DONE_FOLDER_ID || '',
  spreadsheetId: required('SPREADSHEET_ID'),
  pollIntervalMinutes: Number(process.env.POLL_INTERVAL_MINUTES || 10),
  tiktokUseSandbox: process.env.TIKTOK_USE_SANDBOX === 'true',
  tiktokClientKey: process.env.TIKTOK_USE_SANDBOX === 'true'
    ? (process.env.TIKTOK_SANDBOX_CLIENT_KEY || '')
    : (process.env.TIKTOK_CLIENT_KEY || ''),
  tiktokClientSecret: process.env.TIKTOK_USE_SANDBOX === 'true'
    ? (process.env.TIKTOK_SANDBOX_CLIENT_SECRET || '')
    : (process.env.TIKTOK_CLIENT_SECRET || ''),
  xaiApiKey: process.env.XAI_API_KEY || '',
  // API key for the local OmniRoute AI gateway (http://localhost:20128) --
  // copy it from OmniRoute's Dashboard -> Endpoints after connecting a
  // provider. Leave blank if OmniRoute isn't installed; captions/replies
  // just fall back to the built-in templates in that case.
  omnirouteApiKey: process.env.OMNIROUTE_API_KEY || '',
  // Model id OmniRoute expects for its free "Veo AI Free" video provider.
  // Confirm the exact string via OmniRoute's Playground -> Copy cURL (the
  // Model field shown there) if this default ever stops working.
  omnirouteVideoModel: process.env.OMNIROUTE_VIDEO_MODEL || 'veo',
  // Optional hard backup for captions/replies/video concepts, used only when
  // OmniRoute itself doesn't answer (app not running, Mac asleep) rather
  // than routing through it -- so it works even when OmniRoute can't. Get a
  // key at console.anthropic.com (separate signup/billing from a claude.ai
  // subscription). Leave blank to skip this and fall back straight to the
  // built-in templates, same as before this existed.
  anthropicApiKey: process.env.ANTHROPIC_API_KEY || '',
  anthropicModel: process.env.ANTHROPIC_MODEL || 'claude-haiku-4-5-20251001',
  autoGenerateVideos: process.env.AUTO_GENERATE_VIDEOS === 'true',
  autoGenerateDailyLimit: Number(process.env.AUTO_GENERATE_DAILY_LIMIT || 1),
  autoGenerateDurationSeconds: Number(process.env.AUTO_GENERATE_DURATION_SECONDS || 5),
  autoGenerateAspectRatio: process.env.AUTO_GENERATE_ASPECT_RATIO || '9:16',
  // Which hour(s) of the day (0-23, this Mac's local time) to aim auto-generation
  // at -- only the first AUTO_GENERATE_DAILY_LIMIT of these are actually used.
  // Defaults to morning/early afternoon/evening, same as before this setting existed.
  autoGenerateHours: (process.env.AUTO_GENERATE_HOURS || '8,13,18')
    .split(',')
    .map((h) => Number(h.trim())),
  // Independent Pinterest posting for GK_TERMINAL videos, separate from
  // Make.com's own Pinterest posting for GK_JING videos -- this is a
  // deliberately slow, capped test rollout (see PINTEREST_DAILY_LIMIT)
  // while Joe's new trial API access proves itself out.
  pinterestClientId: process.env.PINTEREST_CLIENT_ID || '',
  pinterestClientSecret: process.env.PINTEREST_CLIENT_SECRET || '',
  pinterestBoardId: process.env.PINTEREST_BOARD_ID || '987484724485476675',
  pinterestDailyLimit: Number(process.env.PINTEREST_DAILY_LIMIT || 2),
};
