import 'dotenv/config';

function required(name) {
  const value = process.env[name];
  if (!value) {
    console.error(`Missing required setting: ${name}. Check your .env file (copy .env.example to .env and fill it in).`);
    process.exit(1);
  }
  return value;
}

export const config = {
  googleClientId: required('GOOGLE_CLIENT_ID'),
  googleClientSecret: required('GOOGLE_CLIENT_SECRET'),
  driveFolderId: required('DRIVE_FOLDER_ID'),
  doneFolderId: process.env.DONE_FOLDER_ID || '',
  mirrorFolderId: process.env.MIRROR_FOLDER_ID || '',
  // GK_JING's folder ID -- set this (independent of MIRROR_FOLDER_ID/mirroring)
  // so the script writes missing caption rows for GK_JING videos too, not
  // just its own GK_TERMINAL ones. Leave blank to skip this and only
  // caption GK_TERMINAL videos as before.
  gkJingFolderId: process.env.GK_JING_FOLDER_ID || '',
  canvaClientId: process.env.CANVA_CLIENT_ID || '',
  canvaClientSecret: process.env.CANVA_CLIENT_SECRET || '',
  canvaBrandTemplateId: process.env.CANVA_BRAND_TEMPLATE_ID || '',
  canvaTitleField: process.env.CANVA_TITLE_FIELD || 'title',
  pinterestCoversFolderId: process.env.PINTEREST_COVERS_FOLDER_ID || '',
  // The Make.com side's own done folder (GK_JING_DONE) -- mirroring needs to
  // know about it too, otherwise a video that's already finished on one side
  // and moved to its done folder looks "missing" to the still-pending other
  // side and gets copied right back, causing a duplicate post loop.
  mirrorDoneFolderId: process.env.MIRROR_DONE_FOLDER_ID || '',
  spreadsheetId: required('SPREADSHEET_ID'),
  pollIntervalMinutes: Number(process.env.POLL_INTERVAL_MINUTES || 10),
  tiktokUseSandbox: process.env.TIKTOK_USE_SANDBOX === 'true',
  tiktokClientKey: process.env.TIKTOK_USE_SANDBOX === 'true'
    ? (process.env.TIKTOK_SANDBOX_CLIENT_KEY || '')
    : (process.env.TIKTOK_CLIENT_KEY || ''),
  tiktokClientSecret: process.env.TIKTOK_USE_SANDBOX === 'true'
    ? (process.env.TIKTOK_SANDBOX_CLIENT_SECRET || '')
    : (process.env.TIKTOK_CLIENT_SECRET || ''),
  xaiApiKey: process.env.XAI_API_KEY || '',
  // API key for the local OmniRoute AI gateway (http://localhost:20128) --
  // copy it from OmniRoute's Dashboard -> Endpoints after connecting a
  // provider. Leave blank if OmniRoute isn't installed; captions/replies
  // just fall back to the built-in templates in that case.
  omnirouteApiKey: process.env.OMNIROUTE_API_KEY || '',
  // Model id OmniRoute expects for its free "Veo AI Free" video provider.
  // Confirm the exact string via OmniRoute's Playground -> Copy cURL (the
  // Model field shown there) if this default ever stops working.
  omnirouteVideoModel: process.env.OMNIROUTE_VIDEO_MODEL || 'veo',
  autoGenerateVideos: process.env.AUTO_GENERATE_VIDEOS === 'true',
  autoGenerateDailyLimit: Number(process.env.AUTO_GENERATE_DAILY_LIMIT || 1),
  autoGenerateDurationSeconds: Number(process.env.AUTO_GENERATE_DURATION_SECONDS || 5),
  autoGenerateAspectRatio: process.env.AUTO_GENERATE_ASPECT_RATIO || '9:16',
  // Which hour(s) of the day (0-23, this Mac's local time) to aim auto-generation
  // at -- only the first AUTO_GENERATE_DAILY_LIMIT of these are actually used.
  // Defaults to morning/early afternoon/evening, same as before this setting existed.
  autoGenerateHours: (process.env.AUTO_GENERATE_HOURS || '8,13,18')
    .split(',')
    .map((h) => Number(h.trim())),
};
