import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import fetch from 'node-fetch';
import { config } from './config.js';

const API_BASE = 'https://api.x.ai/v1/videos';
const POLL_INTERVAL_MS = 5000;
const POLL_TIMEOUT_MS = 5 * 60 * 1000;

const DONE_STATUSES = ['completed', 'succeeded', 'success', 'done', 'ready'];
const FAILED_STATUSES = ['failed', 'error', 'cancelled', 'canceled'];

function extractStatus(job) {
  return job.status || job.state || job.data?.status || 'unknown';
}

// xAI's exact response shape for this endpoint isn't publicly documented in a
// way we could verify from here, so this checks every field name the video-gen
// APIs we know about tend to use. If a real response doesn't match any of
// these, the raw JSON gets logged so the right field name can be added.
function extractVideoUrl(job) {
  return (
    job.video_url ||
    job.url ||
    job.video?.url ||
    job.output?.url ||
    job.result?.url ||
    (Array.isArray(job.data) && job.data[0]?.url) ||
    null
  );
}

async function startJob(prompt) {
  const res = await fetch(`${API_BASE}/generations`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${config.xaiApiKey}`,
    },
    body: JSON.stringify({
      model: 'grok-imagine-video-1.5',
      prompt,
      duration: config.autoGenerateDurationSeconds,
      aspect_ratio: config.autoGenerateAspectRatio,
      resolution: '720p',
    }),
  });
  const data = await res.json();
  if (!res.ok) {
    throw new Error(`Grok video request failed: ${data.error?.message || res.status}`);
  }
  const requestId = data.request_id || data.id;
  if (!requestId) {
    throw new Error(`Grok video request didn't return a request id: ${JSON.stringify(data)}`);
  }
  return requestId;
}

async function pollJob(requestId) {
  const deadline = Date.now() + POLL_TIMEOUT_MS;
  while (Date.now() < deadline) {
    const res = await fetch(`${API_BASE}/${requestId}`, {
      headers: { Authorization: `Bearer ${config.xaiApiKey}` },
    });
    const data = await res.json();
    if (!res.ok) {
      throw new Error(`Grok video status check failed: ${data.error?.message || res.status}`);
    }

    const status = String(extractStatus(data)).toLowerCase();
    if (DONE_STATUSES.includes(status)) {
      const url = extractVideoUrl(data);
      if (!url) {
        throw new Error(`Grok video finished but no video URL was found in the response: ${JSON.stringify(data)}`);
      }
      return url;
    }
    if (FAILED_STATUSES.includes(status)) {
      throw new Error(`Grok video generation failed: ${data.error?.message || status}`);
    }

    await new Promise((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
  }
  throw new Error('Grok video generation timed out after 5 minutes');
}

// Generates a short video with xAI's Grok Imagine API and saves it to a temp
// file, returning the local path. Costs real money per call (roughly a few
// cents per second of video at current pricing) -- only call this behind the
// AUTO_GENERATE_VIDEOS opt-in and daily cap in config.
export async function generateVideo(prompt) {
  if (!config.xaiApiKey) {
    throw new Error('XAI_API_KEY is not set -- add it to .env to enable auto video generation.');
  }

  const requestId = await startJob(prompt);
  const videoUrl = await pollJob(requestId);

  const destPath = path.join(os.tmpdir(), `gk-grok-${requestId}.mp4`);
  const videoRes = await fetch(videoUrl);
  if (!videoRes.ok) {
    throw new Error(`Could not download the generated video: ${videoRes.status}`);
  }
  const dest = fs.createWriteStream(destPath);
  await new Promise((resolve, reject) => {
    videoRes.body.pipe(dest).on('finish', resolve).on('error', reject);
  });

  return destPath;
}
